### ISSUE TITLE
Search autocompletion suggests deprecated packages

### ISSUE THREAD

**Issue by michaelbazos** [npm/www#301]
Search autocompletion suggests deprecated packages. Deprecated package can even appear first, see below for a reproduction of the issue.

## Link to the page

https://www.npmjs.com/

## Expected behavior

Deprecated packages should not show up in the autocompletion

## Actual behavior

Search autocompletion suggest deprecated packages

## Steps to reproduce the problem

1. Go to https://www.npmjs.com/
2. Type `angular-feather`
3. First result is `angular-feather-icons` which is a deprecated package

![image](https://user-images.githubusercontent.com/4216141/35770983-db6f2810-0925-11e8-889a-79db982f9b9b.png)

**Comment by jdalton** [comment]
[Fixed](https://twitter.com/jdalton/status/978690078267461632) 🎉

**Comment by michaelbazos** [comment]
@jdalton 

Actually, it's not fixed :)

The search autocompletion still suggests deprecated packages.
What is new is the prominent red warning on the package page, that you highlight in the tweet. That is definitely a welcome change.

As a side note, deprecated packages do not show up in search result pages (it was already the case at the date of opening this issue)

**Comment by jdalton** [comment]
Hmm, it's filtering out my autocomplete search results for my recently deprecated package.

**Comment by michaelbazos** [comment]
I tried with **angular-feather-icons** and **deflate-crc32-stream**

**Comment by jdalton** [comment]
Hmm maybe they need to rebuild a cache or smth on their end.
