### ISSUE TITLE
Unable to find a readme after npm publish

### ISSUE THREAD

**Issue by qianzhao** [npm/www#395]
## I'm opening this issue because:
npm is doing something I don't understand.

## Issue
I just published the package as I always did, I didn't get errors or problems.
But npm no longer find readme file after npm publish:
I got the following messages shows up since then:

> Unable to find a readme for @digital-working-lab/eslint-config-boostmyapps@1.1.8

## supporting information:

- npm -v prints: 5.6.0
- node -v prints: 8.6.0
- npm config get registry prints: https://registry.npmjs.org/
- Mac OS

**Comment by cronvel** [comment]
Same here.
After `npm publish`, the website does not find my README.md anymore.
By the way the repo on Github has it, and I confirm that if I `npm install` it, the README.md file is here.

I never had any issue with README.md until now...

My package is [nextgen-events](https://www.npmjs.com/package/nextgen-events) ([here on Github](https://github.com/cronvel/nextgen-events)).

**Comment by qianzhao** [comment]
@cronvel  i have the same issue you.
And if I download the package from the registry using npm install, the README.md is contained normally as I expect.

**Comment by AlbertHambardzumyan** [comment]
Same here for private package

**Comment by GregOnNet** [comment]
Hi,

I experience the same problem publishing my package: [kentan-schematics](https://www.npmjs.com/package/kentan-schematics)

If I click `test in your browser` and ope RunKit the README is displayed as expected: [RunKit + kentan-schematics](https://npm.runkit.com/kentan-schematics)

**EDIT**
Meanwhile, my README is shown. Maybe it takes a while after publishing a package.

**EDIT 2**
After updating my package the README was not displayed but reappeared after a few minutes.

**Comment by SlexAxton** [comment]
this also happened to the release of https://www.npmjs.com/package/css I just did

**Comment by cronvel** [comment]
Same here: it was not working for 30min, then suddenly the README.md page appeared.

**Comment by hodgef** [comment]
Indeed, I raised this issue earlier a few days ago but it fixed itself after several minutes.. It must have been broken this week, since last week this didn't happen. Very annoying issue, especially since GitHub is updated immediately.

https://github.com/npm/npm/issues/20469

![capture2](https://user-images.githubusercontent.com/25509135/39537710-5ea4f152-4e08-11e8-928f-dedce8ce5e17.PNG)
![capture](https://user-images.githubusercontent.com/25509135/39537711-5eb2b620-4e08-11e8-85d2-b01b12b4bec5.PNG)

**Comment by jefflembeck** [comment]
Hey all, thanks for pointing this out. We've got a fix in and the issue should be resolved shortly. Let us know if this happens again.

**Comment by AlbertHambardzumyan** [comment]
Does this fix reflect on private packages as well?
I still do have it broken for my private package published few hours ago 
`"Unable to find a readme for ...`

**Comment by danielmeneses** [comment]
Hi all,
yes, same here. published just now and I'm getting that missing readme msg. https://www.npmjs.com/package/graphql-authorization

**Comment by melanieseltzer** [comment]
Hi, me too. https://www.npmjs.com/package/grammarize
Hasn't resolved yet, been over an hour since publishing.

**Comment by BernhardBehrendt** [comment]
Hi same here https://www.npmjs.com/package/fetchbot 

Had this very often the last months and mostly solved by a version increase and publish again. But today it won't work.

**Comment by AlbertHambardzumyan** [comment]
I think @jefflembeck was in a hurry to close the issue and have not mentioned that it's not gonna reflect on already published ones. I saw many packages are published again after he mentioned about the fix and it works for them.
So, my assumption is that we need to re-publish te get it affected, which might be a weird solution.

**Comment by BernhardBehrendt** [comment]
3rd time re-publish within one hour.. so cannot confirm it's working.

https://www.npmjs.com/package/fetchbot

But doing a test like this:

```shell
mkdir test
cd ./test
npm init -y
npm install --save fetchbot

cat ./node_modules/fetchbot/README.md
```

Shows up the README.md file is present in the package.

![bildschirmfoto 2018-05-03 um 09 53 33](https://user-images.githubusercontent.com/1717382/39565366-f3741254-4eb7-11e8-914a-cfc46b344861.png)

**Comment by melanieseltzer** [comment]
My readme is back 😄 I never re-published my package so it seems like you don't have to to get it working again.

**Comment by zsoltime** [comment]
Yes, mine are back too and I didn't need to republish them. 😄

**Comment by qianzhao** [comment]
Yes, My readme is back too.
Thanks @jefflembeck

**Comment by jefflembeck** [comment]
This seems to be fixed again. I'm running through every one that I've found submitted so far.

**Comment by AlbertHambardzumyan** [comment]
It got back as I re-published it.

**Comment by technikhil314** [comment]
@jefflembeck I am still facing the issue. Do I need to republish just to get my readme back.
Here is my package https://www.npmjs.com/package/angular-2-daterangepicker.

**Comment by kozhevnikov** [comment]
@nikhil-001mehta your package doesn't have a readme, try `npm pack angular-2-daterangepicker` and check the contents of the tgz.

**Comment by Stradivario** [comment]
So you are Writing README to another server from where you take the info ? In this case server will not have to load the whole GIT repo to show only single README ?

**Comment by postspectacular** [comment]
I'm still encountering this issue with at least 2 packages, both of which have a readme:

- https://www.npmjs.com/package/@thi.ng/hiccup-css
- https://www.npmjs.com/package/@thi.ng/resolve-map

**Comment by nicky-lenaers** [comment]
Still having this issue on https://www.npmjs.com/package/@nicky-lenaers/ngx-scroll-to

**Comment by strouhaljan** [comment]
We also have this issue on https://www.npmjs.com/package/@gooddata/goodstrap :(

**Comment by branderzhai** [comment]
Still having this issue on https://www.npmjs.com/package/@grapecity/spread-sheets

**Comment by strouhaljan** [comment]
Looks like it just takes some time for npm to show readme after releasing. Our readme was fixed overnight.

**Comment by julianobrasil** [comment]
I'm seeing this issue on https://www.npmjs.com/package/@julianobrasil/timemask

**Comment by wulfraem** [comment]
We also have this issue on https://www.npmjs.com/package/@evan.network/dbcp
I can `npm i` it and verify, that the `README.md` is included; the RunKit page shows it as well. Oo

**Comment by jalbertsr** [comment]
we have the same issue too https://www.npmjs.com/package/@kiwicom/smart-faq 

**update:**  just be patient it seems it takes some time for npm to show readme after releasing. Our readme was fixed overnight.

**Comment by rafaelquines** [comment]
Still having this issue on 3 of 4 my packages:

https://www.npmjs.com/package/ledrun
https://www.npmjs.com/package/inputmonitor
https://www.npmjs.com/package/proc-restarter

Can help?

**Comment by wulfraem** [comment]
Fixed for me in latest publish.
I published two versions without the README showing up at all and the latest publish had it instantly.

**Comment by benjamincharity** [comment]
Still seeing this annoying bug https://www.npmjs.com/package/@terminus/ngx-tools

**Comment by kmuthukumar23** [comment]
We are also facing the same issue on https://www.npmjs.com/package/@syncfusion/ej2-grids.

![npm](https://user-images.githubusercontent.com/31958591/41151125-7fd619ae-6b2d-11e8-8bb1-045065555736.png)

can anyone suggests me to resolve this.?

**Comment by muenzpraeger** [comment]
I'm also having this issue since a few versions.

I uploaded a perfectly correct tgz.

https://www.npmjs.com/package/@muenzpraeger/sfdx-plugin

**Comment by nch3ng** [comment]
I'm having this issue: 
https://www.npmjs.com/package/@qqnc/ngx-daterangepicker
Anyone knows why?

**Comment by andreiflaviusivan** [comment]
Hello, Same problem here on my package 
https://www.npmjs.com/package/mindgaze-doublescroll

Readme exists https://github.com/andreiflaviusivan/mindgaze-doublescroll#readme
